# Basic Air configuration for Go projects

[build]
cmd = "go build -o tmp/main.exe ."
bin = "tmp/main.exe"
full_bin = ""
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_file = []
delay = 1000
stop_on_error = true
log = "air.log"

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"